// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0gF6E0VVptjxrHFDn_mvXAWHwaeSoar4',
    appId: '1:735106227800:web:91792b30abc8c38cf0342d',
    messagingSenderId: '735106227800',
    projectId: 'spinroulette-41cea',
    authDomain: 'spinroulette-41cea.firebaseapp.com',
    storageBucket: 'spinroulette-41cea.firebasestorage.app',
    measurementId: 'G-CWGMDEJGYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTAT9cQGsBZOxZAfQ55GcA1AStJk4edG8',
    appId: '1:735106227800:android:7e6dc7c753d00372f0342d',
    messagingSenderId: '735106227800',
    projectId: 'spinroulette-41cea',
    storageBucket: 'spinroulette-41cea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWC_8Q8kYak8N1lyJUpcsvR2cYBG1k5VA',
    appId: '1:735106227800:ios:d4768646cfc07d08f0342d',
    messagingSenderId: '735106227800',
    projectId: 'spinroulette-41cea',
    storageBucket: 'spinroulette-41cea.firebasestorage.app',
    iosBundleId: 'com.example.rouletteNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWC_8Q8kYak8N1lyJUpcsvR2cYBG1k5VA',
    appId: '1:735106227800:ios:d4768646cfc07d08f0342d',
    messagingSenderId: '735106227800',
    projectId: 'spinroulette-41cea',
    storageBucket: 'spinroulette-41cea.firebasestorage.app',
    iosBundleId: 'com.example.rouletteNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0gF6E0VVptjxrHFDn_mvXAWHwaeSoar4',
    appId: '1:735106227800:web:f9c7fd725aa6a5daf0342d',
    messagingSenderId: '735106227800',
    projectId: 'spinroulette-41cea',
    authDomain: 'spinroulette-41cea.firebaseapp.com',
    storageBucket: 'spinroulette-41cea.firebasestorage.app',
    measurementId: 'G-THFFD4GKZZ',
  );

}